apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ryr8
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ryr8
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ryr8
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ryr8
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ryr8
    spec:
      containers:
      - image: quay.io/rh-gitops-bot/rhtap-demo-dwhj-tenant/rhtap-demo-app/hacbs-test-project-ryr8@sha256:1d95ad7922ad7947136c924729d2c540c41010c35e428c27ae39a4574a21970e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
